spring.application.name=PTV


# Server port ? open browser at http://localhost:8080
server.port=8080

# Target JVM connection settings
# Change these if your target program runs on a different host/port
jdi.host=localhost
jdi.port=5005

# Logging
logging.level.com.threadvis=DEBUG
logging.level.org.springframework.web.socket=INFO

# Allow larger WebSocket messages
spring.websocket.max-text-message-size=65536
